export const LIST_ALLCLASS_SUCCESS = 'LIST_ALLCLASS_SUCCESS';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const LIST_ALL_PARTICIPANT_SUCCESS='LIST_ALL_PARTICIPANT_SUCCESS';
export const DELETE_PARTICIPANT_SUCCESS='DELETE_PARTICIPANT_SUCCESS';
export const LIST_ALLATTENDENCE_SUCCESS='LIST_ALLATTENDENCE_SUCCESS';
export const VALID_USER = 'VALID_USER';
export const LOGOUT = 'LOGOUT';
export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
